// Enlaza cada banner a la página del producto
export const heroSlides = [
  {
    id: "apex-1",
    type: "image",
    src: "/banner.webp",
    alt: "Dara Caro - Sweet Obsession Parfum",
    eyebrow: "Obsesión dulce y audaz",
    title: "DARA CARO",
    description: "",
    ctaLabel: "Conoce más",
    ctaHref: "/products/dara-caro-sweet-obsession",
    align: "left",
    theme: "light",
  },
  {
    id: "apex-2",
    type: "image",
    src: "/bannerv2.webp",
    alt: "Parfum NIAREUCE",
    eyebrow: "Tu huella eterna.",
    title: "NIAREUCE",
    description: "",
    ctaLabel: "Conoce más",
    // FIX: usar el slug correcto del producto
    ctaHref: "/products/niareuce-parfum",
    align: "left",
    theme: "light",
  },
  {
    id: "apex-3",
    type: "image",
    src: "/bannerv3.webp",
    alt: "Parfum BERGAMOT NICHE",
    eyebrow: "Frescura pura en cada nota",
    title: "BERGAMOT NICHE",
    description: "",
    ctaLabel: "Conoce más",
    ctaHref: "/products/bergamot-niche",
    align: "left",
    theme: "light",
  },
  {
    id: "apex-4",
    type: "image",
    src: "/bannerv4.webp",
    alt: "Parfum NOCTIS",
    eyebrow: "El misterio hecho fragancia",
    title: "NOCTIS AMÉTHYSTE",
    description: "",
    ctaLabel: "Conoce más",
    ctaHref: "/products/noctis-amethyste",
    align: "left",
    theme: "light",
  },
];