// Lista de tiendas / puntos de venta. Ajusta los datos a tu realidad.
// Puedes agregar o quitar campos sin problema.
export const stores = [
  {
    id: "jockey-plaza",
    name: "ESSENZA Jockey Plaza",
    city: "Lima",
    district: "Santiago de Surco",
    address: "Av. Javier Prado Este 4200, Tienda 123, Jockey Plaza, Lima",
    hours: "Lun-Dom 10:00–21:00",
    phone: "+51 918 605 351",
    whatsapp: "https://wa.me/51918605351?text=Hola%20ESSENZA%2C%20quiero%20informaci%C3%B3n%20del%20punto%20de%20venta%20Jockey%20Plaza",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Jockey+Plaza+Lima",
    type: "Tienda física",
    notes: "Ubicados en el primer nivel, frente al patio central.",
  },
  {
    id: "miraflores-larcomar",
    name: "ESSENZA Larcomar",
    city: "Lima",
    district: "Miraflores",
    address: "Malecón de la Reserva 610, Larcomar, Miraflores",
    hours: "Lun-Dom 10:00–22:00",
    phone: "+51 918 605 351",
    whatsapp: "https://wa.me/51918605351?text=Hola%20ESSENZA%2C%20informaci%C3%B3n%20de%20Larcomar%20por%20favor",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Larcomar+Miraflores",
    type: "Tienda física",
    notes: "Excelente para probar fragancias con vista al mar.",
  },
  {
    id: "arequipa-mall",
    name: "ESSENZA Arequipa Mall",
    city: "Arequipa",
    district: "Cercado",
    address: "Av. Ejército 793, Mall Aventura Arequipa",
    hours: "Lun-Dom 10:00–21:00",
    phone: "+51 918 605 351",
    whatsapp: "https://wa.me/51918605351?text=Hola%20ESSENZA%2C%20consulta%20sobre%20Arequipa%20Mall",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Mall+Aventura+Arequipa",
    type: "Tienda física",
  },
  {
    id: "trujillo-real-plaza",
    name: "ESSENZA Real Plaza Trujillo",
    city: "Trujillo",
    district: "Victor Larco",
    address: "Av. César Vallejo 1345, Real Plaza Trujillo",
    hours: "Lun-Dom 10:00–21:00",
    phone: "+51 918 605 351",
    whatsapp: "https://wa.me/51918605351?text=Hola%20ESSENZA%2C%20informaci%C3%B3n%20de%20Trujillo",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Real+Plaza+Trujillo",
    type: "Tienda física",
  },
  {
    id: "venta-online",
    name: "Venta Online y Envíos",
    city: "Todo el Perú",
    district: "",
    address: "Despacho desde Lima a todo el país",
    hours: "24/7 en la web",
    phone: "",
    whatsapp: "https://wa.me/51918605351?text=Hola%20ESSENZA%2C%20necesito%20ayuda%20con%20mi%20compra%20online",
    mapUrl: "https://www.essenza.pe/",
    type: "Online",
    notes: "Envíos gratis superando el monto mínimo.",
  },
];